# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmslerGrid',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular amsler grid', primary_key=True, serialize=False)),
                ('verify_date', models.DateField(blank=True, null=True)),
                ('amsler_score', models.IntegerField(verbose_name='Amsler_score')),
                ('status', models.CharField(blank=True, choices=[('v', 'Verified'), ('u', 'Unverified')], default='u', help_text='Amsler Grid Status', max_length=1)),
            ],
            options={
                'ordering': ['verify_date'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.TextField(help_text='Enter a brief address of patient', max_length=400)),
                ('age', models.IntegerField(verbose_name='AGE')),
                ('contact_no', models.TextField(help_text='Select contact number', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='amslergrid',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userlist.Patient'),
        ),
    ]
