# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a hospital name (e.g. KMC Manipal)', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userlist.Doctor'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact_no',
            field=models.CharField(help_text='Select contact number', max_length=10),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ManyToManyField(blank=True, help_text='Select the hospital to which the doctor belongs', to='userlist.Hospital'),
        ),
    ]
