# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 04:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userlist', '0002_auto_20170222_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
