# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-17 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlist', '0006_patient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='amslergrid',
            name='grid1',
            field=models.ImageField(blank=True, null=True, upload_to='grid/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='fundus_photo',
            field=models.ImageField(blank=True, null=True, upload_to='fundus/'),
        ),
    ]
